name: private_notes_light
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
  


  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  equatable: ^2.0.8
  meta: ^1.17.0
  uuid: ^4.5.2
  encrypt: ^5.0.3
  shared_preferences: ^2.5.4
  crypto: ^3.0.7
  sqflite: ^2.4.2
  path: ^1.9.1
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  intl: ^0.20.2
  file_picker: ^10.3.10
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  cryptography: ^2.9.0
  cryptography_flutter: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.4.6
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  json_serializable: ^6.9.5
  freezed: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

